package compiler;

public enum TokenType {
//Single char tokens
LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR, COLON, VERTICAL_LINE, 

//One or two character tokens.
BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, ASSIGNMENT, RANGE_SEPARATOR, ASSIGN,

//LITERALS.
IDENTIFIER, STRING, NUMBER, TYPE_REFERENCE, RESERVE_WORD,

//KEYWORDS.
AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, OR, PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE, TAGS, BEGIN, SEQUENCE, INTEGER, DATE, END,

EOF
}
